Repository NOAA-GFDL/FMS, pull requests merged in 2019-12, with the labels that each got.

#196 __APPLE__ replaced with autoconf test for gettid
  affinity/affinity.c
  configure.ac
Labels: bug

#207 now check for sed and ncgen in configure.ac
  configure.ac
Labels: enhancement

#229 fix circular depedency related to mpp_efp_mod.mod
  mpp/Makefile.am
Labels: bug

#233 Fixed pull request template so it shows
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#236 new io: amip_interp with no scale factor
  amip_interp/amip_interp.F90
Labels: new fms io

#232 Fix CPP warning
  mpp/include/mpp_comm_mpi.inc
Labels: bug

#245 Fix quad precision issue with hard on/off switch
  include/fms_platform.h
  interpolator/interpolator.F90
  mosaic/create_xgrid.c
  mosaic/mosaic_util.c
Labels: bug
