Repository NOAA-GFDL/FMS, pull requests merged in 2019-11, with the labels that each got.

#215 addresses issues #210 & #214
  block_control/block_control.F90
  include/fms_platform.h
Labels: bug fix, enhancement

#216 FMS IO: Fill value logic check separation
  mpp/include/mpp_io_write.inc
Labels: bug fix

#218 Fix GNU compiler warnings
  mpp/include/mpp_domains_define.inc
  mpp/include/mpp_io_write.inc
Labels: enhancement

#219 updated makefile for use with current EMC build system
  fv3gfs/makefile
Labels: enhancement
