Repository NOAA-GFDL/FMS, pull requests merged in 2020-08, with the labels that each got.

#538 Add ifdef for use_mpp_io to diag manager modules
  diag_manager/diag_data.F90
  diag_manager/diag_manager.F90
  diag_manager/diag_output.F90
  diag_manager/diag_util.F90
Labels: feature request

#459 WIP Stdout Unit Test
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_stdout.F90
  test_fms/mpp/test_stdout.sh
Labels: development

#556 mpp: BOZ literal assignment
  mpp/mpp_domains.F90
  mpp/mpp_parameter.F90
Labels: enhancement

#554 Topography fix for mpp io
  topography/topography.F90
Labels: feature request

#557 Add miscellaneous mpp-io ifdef's
  diag_integral/diag_integral.F90
  diag_manager/diag_data.F90
  field_manager/field_manager.F90
  fms/fms.F90
  test_fms/data_override/test_data_override_ongrid.F90
  test_fms/fms2_io/test_atmosphere_io.F90
  test_fms/fms2_io/test_fms2_io.F90
  test_fms/fms2_io/test_get_mosaic_tile_grid.F90
  test_fms/fms2_io/test_global_att.F90
  test_fms/fms2_io/test_io_simple.F90
  test_fms/fms2_io/test_io_with_mask.F90
Labels: enhancement

#552 Checks for null character after reading a string from a netcdf file
  fms2_io/fms_io_utils.F90
  fms2_io/include/get_global_attribute.inc
  fms2_io/include/get_variable_attribute.inc
  test_fms/fms2_io/test_global_att.F90
Labels: bug

#550 data_override[2] array size mismatch crash
  data_override/data_override.F90
  test_fms/data_override/test_data_override2.sh
  test_fms/data_override/test_data_override_ongrid.F90
Labels: bug

#553 Removes commented code from diag_output and diag_util
  diag_manager/diag_output.F90
  diag_manager/diag_util.F90
Labels: enhancement

#560 Updates CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#563 Message to check which IO is used
  fms/fms.F90
Labels: documentation

#564 Mpp get ascii lines unit test changes
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_mpp_get_ascii_lines.F90
  test_fms/mpp/test_mpp_get_ascii_lines2.sh
Labels: enhancement

#423 read_input_nml unit test
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_read_input_nml.F90
  test_fms/mpp/test_read_input_nml2.sh
Labels: development

#446 Test read ascii file
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_read_ascii_file.F90
  test_fms/mpp/test_read_ascii_file.sh
Labels: development

#566 Change mpirun to run_test in test_mpp_memutils.sh
  test_fms/mpp/input_base.nml
  test_fms/mpp/test_mpp_memutils_mod.sh
Labels: enhancement
