Repository NOAA-GFDL/FMS, pull requests merged in 2020-01, with the labels that each got.

#251 Remove string overflow warning in field_manager
  field_manager/field_manager.F90
Labels: bug

#187 Use correct c abs function for all variable types
  mosaic/create_xgrid.c
  mosaic/mosaic_util.c
Labels: bug

#99 Complex support for mpp_sum, alltoallw, type
  mpp/include/mpp_comm_mpi.inc
  mpp/include/mpp_domains_reduce.inc
  mpp/mpp.F90
Labels: feature request

#253 Io master merge
  field_manager/field_manager.F90
  mosaic/create_xgrid.c
  mosaic/mosaic_util.c
  mpp/include/mpp_comm_mpi.inc
  test_fms/Makefile.am
Labels: new fms io

#240 fix last of namelist copy issues during testing
  test_fms/Makefile.am
  test_fms/diag_manager/Makefile.am
Labels: bug

#257 Remove oda_tools directory and source
  Makefile.am
  configure.ac
  fv3gfs/makefile
  libFMS/Makefile.am
  oda_tools/Makefile.am
  oda_tools/oda_core.F90
  oda_tools/oda_core_ecda.F90
  oda_tools/oda_types.F90
  oda_tools/write_ocean_data.F90
  oda_tools/xbt_drop_rate_adjust.f90
Labels: suggestion

#258 quad precision merge conflict resolution
  include/fms_platform.h
  interpolator/interpolator.F90
  mosaic/mosaic_util.c
Labels: bug

#146 No extra xy
  fms2_io/include/domain_write.inc
Labels: development

#191 remove unused variables in some c sources
  mosaic/create_xgrid.c
  mosaic/interp.c
Labels: development

#260 Add codeowners file
  .github/CODEOWNERS
Labels: enhancement

#238 Removes mpirun as the default mpi launcher
  configure.ac
  test_fms/axis_utils/test_axis_utils2.sh
  test_fms/data_override/test_data_override2.sh
  test_fms/diag_manager/test_diag_manager2.sh
  test_fms/drifters/test_drifters2.sh
  test_fms/exchange/test_xgrid2.sh
  test_fms/fft/test_fft2.sh
  test_fms/field_manager/test_field_manager2.sh
  test_fms/fms/test_fms_io2.sh
  test_fms/horiz_interp/test_horiz_interp2.sh
  test_fms/interpolator/test_interpolator2.sh
  test_fms/monin_obukhov/test_monin_obukhov2.sh
  test_fms/mosaic/test_mosaic2.sh
  test_fms/mpp/test_mpp2.sh
  test_fms/mpp/test_mpp_domains2.sh
  test_fms/mpp/test_mpp_pset2.sh
  test_fms/mpp_io/test_mpp_io2.sh
  test_fms/test_common.sh.in
  test_fms/time_interp/test_time_interp2.sh
  test_fms/time_manager/test_time_manager2.sh
Labels: enhancement

#199 Remove unused components - fft, station_data, diag_manager/diag_manifest.F90
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  FMS.pc.in
  Makefile.am
  configure.ac
  diag_manager/Makefile.am
  diag_manager/diag_data.F90
  diag_manager/diag_manager.F90
  diag_manager/diag_manifest.F90
  fft/Makefile.am
  fft/fft.F90
  fft/fft99.F90
  fv3gfs/makefile
  libFMS/Makefile.am
  m4/gx_fortran_options.m4
  test_fms/Makefile.am
  test_fms/fft/Makefile.am
  test_fms/fft/input_base.nml
  test_fms/fft/test_fft.F90
Labels: development, enhancement
