Repository NOAA-GFDL/FMS, pull requests merged in 2020-07, with the labels that each got.

#461 More testing for fms2_io
  test_fms/fms2_io/test_io_simple.F90
Labels: development

#453 Adds levels to mpp_init to return at a certain point
  mpp/include/mpp_comm_mpi.inc
  mpp/mpp.F90
Labels: enhancement, feature request

#449 Clock_init Unit Test
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_clock_init.F90
  test_fms/mpp/test_clock_init.sh
Labels: development

#401 Adds mpp broadcast
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_mpp.F90
  test_fms/mpp/test_mpp_broadcast.F90
  test_fms/mpp/test_mpp_broadcast.sh
Labels: development

#429 Adds test_system_clock unit test
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_system_clock.F90
  test_fms/mpp/test_system_clock.sh
Labels: development

#444 Adds unit test for get_ascii_file_num_lines (now works with Travis)
  test_fms/mpp/Makefile.am
  test_fms/mpp/base_ascii_0
  test_fms/mpp/base_ascii_25
  test_fms/mpp/base_ascii_5
  test_fms/mpp/base_ascii_long
  test_fms/mpp/base_ascii_skip
  test_fms/mpp/input_base.nml
  test_fms/mpp/test_mpp_get_ascii_lines.F90
  test_fms/mpp/test_mpp_get_ascii_lines2.sh
Labels: development

#491 Fix dependency issues in fms2_io and include files
  fms2_io/Makefile.am
Labels: enhancement

#472 Added new macro for correct definition of transfer intrinsic mold
  mpp/include/mpp_chksum.h
  mpp/include/mpp_comm.inc
Labels: bug

#467 fms2io: optional argument to not add ".res" to filename
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/fms_netcdf_unstructured_domain_io.F90
  fms2_io/netcdf_io.F90
Labels: development, enhancement

#493 Add doxygen to the build system
  Makefile.am
  configure.ac
  docs/Doxyfile.in
  docs/Makefile.am
Labels: enhancement

#512 Checks to prevent time_bnds from being overwritten
  diag_manager/diag_util.F90
Labels: bug

#520 Author updates
  test_fms/mpp/test_mpp_broadcast.sh
  test_fms/mpp/test_mpp_get_ascii_lines2.sh
Labels: documentation

#529 Update version numbers for 2019.01.03 release
  configure.ac
  libFMS/Makefile.am
Labels: documentation

#531 Update release version numbers with "-dev"
  configure.ac
  libFMS/Makefile.am
Labels: documentation

#526 Adds --enable-mpp-io flag to configuration script
  .travis.yml
  configure.ac
Labels: feature request

#489 Adds support to read in string global attributes
  fms2_io/include/get_global_attribute.inc
  fms2_io/include/register_global_attribute.inc
  test_fms/fms2_io/Makefile.am
  test_fms/fms2_io/test_global_att.F90
  test_fms/fms2_io/test_global_att.sh
Labels: development, enhancement

#494 now require netCDF to have been built with HDF5
  configure.ac
Labels: enhancement

#469 Adds unit test for mpp_root_pe()
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_mpp_root_pe.F90
  test_fms/mpp/test_mpp_root_pe.sh
Labels: development

#393 Adds unit test for mpp_pe
  test_fms/mpp/test_mpp_pe.F90
  test_fms/mpp/test_mpp_pe.sh
Labels: enhancement

#457 Unit test for stderr
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_stderr.F90
  test_fms/mpp/test_stderr.sh
Labels: development

#527 Update test_mpp_domains2.sh to work
  test_fms/mpp/test_mpp_domains2.sh
Labels: bug, development

#504 bugfix on cmake in the master.
  .gitignore
  .travis.yml
  CMAKE_INSTRUCTIONS.md
  CMakeLists.txt
  FMSConfig.cmake.in.in
  FMSConfigVersion.cmake.in.in
  Makefile.am
  _package_init_cmake
  cmake/FMSConfig.cmake.in
  cmake/FindNetCDF.cmake
  cmake/compiler_flags_Clang_C.cmake
  cmake/compiler_flags_GNU_C.cmake
  cmake/compiler_flags_GNU_Fortran.cmake
  cmake/compiler_flags_Intel_C.cmake
  cmake/compiler_flags_Intel_Fortran.cmake
  cmake/fms_compiler_flags.cmake
  configure.ac
Labels: bug

#524 Adds -Duse_mpp_io to amip_interp.F90
  amip_interp/amip_interp.F90
Labels: enhancement

#535 Domain read fix
  fms2_io/include/domain_read.inc
  test_fms/fms2_io/test_io_with_mask.F90
Labels: new fms io

#522 Adds -Duse_mpp_io to xgrid.F90 for use with mpp_io and fms2_io
  exchange/xgrid.F90
Labels: feature request

#525 Adds -Duse_mpp_io to interpolator.F90
  interpolator/interpolator.F90
Labels: enhancement

#515 Data override fix
  data_override/data_override.F90
  test_fms/data_override/Makefile.am
  test_fms/data_override/test_data_override2.sh
  test_fms/data_override/test_data_override_ongrid.F90
  time_interp/time_interp_external2.F90
Labels: development, enhancement

#400 User/jml/add peset test
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_peset.F90
  test_fms/mpp/test_peset.sh
Labels: enhancement

#536 add pgi support to fms2io
  diag_manager/diag_output.F90
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/include/get_variable_attribute.inc
  fms2_io/include/register_global_attribute.inc
  fms2_io/include/register_variable_attribute.inc
  test_fms/fms2_io/atmosphere_restart_file_test.inc
  test_fms/fms2_io/land_compressed_restart_file_test.inc
  test_fms/fms2_io/land_unstructured_restart_file_test.inc
  test_fms/fms2_io/ocean_restart_file_test.inc
  test_fms/fms2_io/test_atmosphere_io.F90
  test_fms/fms2_io/test_global_att.F90
Labels: bug

#412 Update configure.ac
  configure.ac
Labels: development

#541 Fix call for mpp-io flag
  configure.ac
Labels: enhancement
