Repository NOAA-GFDL/FMS, pull requests merged in 2020-06, with the labels that each got.

#398 Change write_restart to write out all meta_data before data
  fms2_io/fms_netcdf_domain_io.F90
Labels: bug

#419 Interpolator cleanup
  interpolator/interpolator.F90
Labels: development, suggestion

#434 Fixes regional diagnostic error (issue # 409) by adding global attrib…
  diag_manager/diag_output.F90
Labels: bug, development

#431 Improve FMS2 I/O domain-decomposed write performance
  fms2_io/include/domain_write.inc
Labels: development

#408 One line change to enable 3D Data Override
  time_interp/time_interp_external2.F90
Labels: enhancement

#427 Adds the netcdf buffer as a namelist and uses it in nf90_enddef
  fms2_io/fms2_io.F90
  fms2_io/netcdf_io.F90
Labels: enhancement

#433 fms2io: add netcdf file type to namelist
  diag_manager/diag_output.F90
  fms2_io/fms2_io.F90
  fms2_io/netcdf_io.F90
Labels: development

#451 Very basic I/O test for fms2_io
  test_fms/fms2_io/Makefile.am
  test_fms/fms2_io/test_io_simple.F90
  test_fms/fms2_io/test_io_simple.sh
Labels: development

#476 Building and exporting FMS library with CMake
  CMAKE_INSTRUCTIONS.md
  CMakeLists.txt
  FMSConfig.cmake.in.in
  FMSConfigVersion.cmake.in.in
  Makefile.am
  _package_init_cmake
  configure.ac
Labels: enhancement

#456 Uses iso_fortran_env values for in, out, and error
  mpp/mpp.F90
Labels: bug, enhancement, feature request

#475 added include dependencies for mpp mod files
  mpp/Makefile.am
Labels: development, enhancement

#465 Changes axis to float in diag manager
  diag_manager/diag_output.F90
Labels: bug, feature request, new fms io

#478 simple test for mpp_domains
  test_fms/mpp/Makefile.am
  test_fms/mpp/test_domains_simple.F90
  test_fms/mpp/test_mpp_domains2.sh
Labels: development
