Repository NOAA-GFDL/FMS, pull requests merged in 2020-03, with the labels that each got.

#329 User/jml/add axis registration check
  fms2_io/fms2_io.F90
  fms2_io/fms_netcdf_domain_io.F90
Labels: enhancement, new fms io

#332 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#342 Modify get_global_io_domain_indices to output buffer of axis data
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/netcdf_io.F90
Labels: enhancement

#337 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#227 Nest updates for FMS
  .gitlab-ci.yml
  .gitlab/issue_templates/Bug.md
  .gitlab/merge_request_templates/Default.md
  CHANGELOG.md
  amip_interp/amip_interp.F90
  axis_utils/axis_utils2.F90
  column_diagnostics/column_diagnostics.F90
  diag_integral/Makefile.am
  diag_integral/diag_integral.F90
  diag_integral/diag_integral.html
  diag_manager/diag_manager.F90
  diag_manager/diag_output.F90
  diag_manager/diag_util.F90
  doxyfile
  exchange/xgrid.F90
  fms2_io/fms_io_utils.F90
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/include/compressed_write.inc
  fms2_io/include/domain_write.inc
  fms2_io/include/get_global_attribute.inc
  fms2_io/netcdf_io.F90
  include/fms_platform.h
  interpolator/interpolator.F90
  monin_obukhov/monin_obukhov.F90
  monin_obukhov/monin_obukhov.html
  monin_obukhov/monin_obukhov.tech.ps
  mosaic/mosaic2.F90
  mpp/include/mpp_define_nest_domains.inc
  mpp/include/mpp_do_update_nest.h
  mpp/include/mpp_domains_define.inc
  mpp/include/mpp_domains_misc.inc
  mpp/include/mpp_domains_util.inc
  mpp/include/mpp_io_write.inc
  mpp/include/mpp_update_nest_domains.h
  mpp/mpp_domains.F90
  sat_vapor_pres/sat_vapor_pres.F90
  test_fms/affinity/test_affinity2.sh
  test_fms/diag_manager/test_diag_manager2.sh
  test_fms/drifters/drifters_inp_test_3d.cdl
  test_fms/exchange/test_xgrid.F90
  test_fms/fft/test_fft2.sh
  test_fms/fms2_io/Makefile.am
  test_fms/fms2_io/argparse.F90
  test_fms/fms2_io/test_atmosphere_io.bats
  test_fms/mpp/input_base.nml
  test_fms/mpp/test_mpp_domains.F90
  test_fms/mpp/test_mpp_domains2.sh
  test_fms/mpp_io/input_base.nml
  test_fms/mpp_io/test_mpp_io2.sh
  test_fms/test_common.sh.in
  test_fms/time_interp/test_time_interp2.sh
  test_fms/time_manager/test_time_manager2.sh
  time_interp/time_interp_external2.F90
  topography/topography.F90
Labels: enhancement

#349 fms2io: removes fileobj%is_root = .false. in netcdf_io.F90
  fms2_io/netcdf_io.F90
Labels: new fms io

#344 test_diag_manager2.sh Fix
  diag_manager/diag_manager.F90
  test_fms/diag_manager/test_diag_manager.F90
  test_fms/diag_manager/test_diag_manager2.sh
Labels: bug, development

#360 Adding License Information to fms2_io
  fms2_io/blackboxio.F90
  fms2_io/fms2_io.F90
  fms2_io/fms_io_utils.F90
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/fms_netcdf_unstructured_domain_io.F90
  fms2_io/include/array_utils.inc
  fms2_io/include/array_utils_char.inc
  fms2_io/include/compressed_read.inc
  fms2_io/include/compressed_write.inc
  fms2_io/include/compute_global_checksum.inc
  fms2_io/include/domain_read.inc
  fms2_io/include/domain_write.inc
  fms2_io/include/get_checksum.inc
  fms2_io/include/get_data_type_string.inc
  fms2_io/include/get_global_attribute.inc
  fms2_io/include/get_variable_attribute.inc
  fms2_io/include/netcdf_add_restart_variable.inc
  fms2_io/include/netcdf_read_data.inc
  fms2_io/include/netcdf_write_data.inc
  fms2_io/include/register_domain_restart_variable.inc
  fms2_io/include/register_global_attribute.inc
  fms2_io/include/register_unstructured_domain_restart_variable.inc
  fms2_io/include/register_variable_attribute.inc
  fms2_io/include/unstructured_domain_read.inc
  fms2_io/include/unstructured_domain_write.inc
  fms2_io/netcdf_io.F90
  test_fms/fms2_io/argparse.F90
  test_fms/fms2_io/atmosphere_restart_file_test.inc
  test_fms/fms2_io/create_atmosphere_domain.inc
  test_fms/fms2_io/create_land_domain.inc
  test_fms/fms2_io/create_ocean_domain.inc
  test_fms/fms2_io/land_compressed_restart_file_test.inc
  test_fms/fms2_io/land_unstructured_restart_file_test.inc
  test_fms/fms2_io/ocean_restart_file_test.inc
  test_fms/fms2_io/setup.F90
  test_fms/fms2_io/test_atmosphere_io.F90
  test_fms/fms2_io/test_fms2_io.F90
Labels: documentation

#354 Changes the intent of fileobj from in to inout so the data buffer can…
  fms2_io/blackboxio.F90
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/netcdf_io.F90
Labels: bug

#364 Correct Cray pointer check for autotools
  m4/gx_fortran_options.m4
Labels: bug

#363 add explicit stack/traceback dump calls for FATAL errors
  mpp/include/mpp_util_mpi.inc
Labels: enhancement
