Repository NOAA-GFDL/FMS, pull requests merged in 2020-05, with the labels that each got.

#410 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#405 Update Makefile.am
  libFMS/Makefile.am
Labels: documentation

#402 Update configure.ac
  configure.ac
Labels: documentation

#417 updates fv3fgfs make.rules and makefile
  fv3gfs/make.rules
  fv3gfs/makefile
Labels: bug

#428 Request 2019.01.02 tag on 2019.01 branch, FMS2020.02 diag_axis_init interface changes
  diag_manager/diag_axis.F90
  diag_manager/diag_manager.F90
Labels: development

#440 Update Makefile.am
  libFMS/Makefile.am
Labels: development, documentation
