Repository NOAA-GFDL/FMS, pull requests merged in 2020-02, with the labels that each got.

#273 User/jml/add check for append mode
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/netcdf_io.F90
Labels: bug, new fms io

#283 bugfix where wrong counter was used
  fms2_io/fms_netcdf_domain_io.F90
Labels: bug

#284 Allow calendar "365_DAYS" in addition to "365_DAY"
  time_manager/get_cal_time.F90
Labels: bug

#285 on-grid read indexing fix
  time_interp/time_interp_external2.F90
Labels: bug, new fms io

#279 Change in time_interp_external2 to read the end times correctly
  time_interp/time_interp_external2.F90
Labels: bug

#288 initializes valid%has_missing to .false. to avoid reproducing issues
  fms2_io/netcdf_io.F90
Labels: bug, new fms io

#293 More get valid fix
  fms2_io/netcdf_io.F90
Labels: bug

#286 potential fix for some axis_utils2 issues
  axis_utils/axis_utils2.F90
Labels: bug

#270 Resolves #269. Any variable that was named `pos` is now named `domain_position`
  CHANGELOG.md
  diag_manager/diag_axis.F90
  diag_manager/diag_data.F90
  diag_manager/diag_manager.F90
  diag_manager/diag_output.F90
Labels: enhancement

#296 Update CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#275 Add initial Makdown guides for libFMS
  CODE_OF_CONDUCT.md
  CODE_STYLE.md
  CONTRIBUTING.md
  INSTALL.md
Labels: documentation

#181 Improve autotools build process
  .travis.yml
  configure.ac
  m4/gx_f08_support.m4
  m4/gx_fortran_options.m4
Labels: enhancement

#292 Allows region diagnostic history files to be written
  diag_manager/diag_output.F90
Labels: bug

#298 Correctly broadcast valid%has_missing to other pe ranks
  fms2_io/netcdf_io.F90
Labels: bug

#308 Remove the duplicate setting of use_libMPI and use_netCDF in configure.ac
  configure.ac
Labels: bug

#323 Update release notes related to the diag_manager
  CHANGELOG.md
Labels: documentation

#310 Correct Fortran STOP statement in mpp test programs
  test_fms/mpp/test_mpp_mem_dump.F90
  test_fms/mpp/test_mpp_memuse.F90
Labels: bug

#311 Correct syntax error in test_common.sh.in
  test_fms/test_common.sh.in
Labels: bug

#313 Update .travis.yml file to clear Travis CI warnings
  .travis.yml
Labels: bug

#268 Gfortran4.8.5 bug test
  configure.ac
  m4/gx_compiler_bug_checks.m4
Labels: development

#320 Fix: get_valid and is_valid
  fms2_io/netcdf_io.F90
Labels: bug
