Repository NOAA-GFDL/FMS, pull requests merged in 2020-04, with the labels that each got.

#280 User/jml/update fms2io tests
  test_fms/fms2_io/Makefile.am
  test_fms/fms2_io/atmosphere_restart_file_test.inc
  test_fms/fms2_io/input.nml
  test_fms/fms2_io/test_atmosphere_io.bats
  test_fms/fms2_io/test_atmosphere_io.sh
  test_fms/fms2_io/test_fms2_io.F90
  test_fms/fms2_io/test_fms2_io.bats
  test_fms/fms2_io/test_fms2_io.sh
Labels: enhancement, new fms io

#380 Allow tests that fail on Travis CI to write the test output logs
  .travis.yml
Labels: bug

#365 Clean out deprecated #ifdef statements
  axis_utils/axis_utils2.F90
  drifters/drifters.F90
  horiz_interp/horiz_interp.F90
  interpolator/interpolator.F90
  mosaic/mosaic2.F90
  time_interp/time_interp_external2.F90
Labels: duplicate

#369 Changing "OBJEXT" to "lo" in Makefile.am files for more correct makefiles
  affinity/Makefile.am
  amip_interp/Makefile.am
  astronomy/Makefile.am
  axis_utils/Makefile.am
  block_control/Makefile.am
  column_diagnostics/Makefile.am
  constants/Makefile.am
  coupler/Makefile.am
  data_override/Makefile.am
  diag_integral/Makefile.am
  diag_manager/Makefile.am
  drifters/Makefile.am
  exchange/Makefile.am
  field_manager/Makefile.am
  fms/Makefile.am
  fms2_io/Makefile.am
  horiz_interp/Makefile.am
  interpolator/Makefile.am
  memutils/Makefile.am
  monin_obukhov/Makefile.am
  mosaic/Makefile.am
  mpp/Makefile.am
  platform/Makefile.am
  random_numbers/Makefile.am
  sat_vapor_pres/Makefile.am
  time_interp/Makefile.am
  time_manager/Makefile.am
  topography/Makefile.am
  tracer_manager/Makefile.am
  tridiagonal/Makefile.am
Labels: enhancement

#348 change compute_global_checksum.inc to support `kind=real32`
  fms2_io/fms_netcdf_domain_io.F90
  fms2_io/include/compute_global_checksum.inc
Labels: development, new fms io

#376 Replace fms_platform.h with platform_mod in diag_manager
  block_control/block_control.F90
  data_override/data_override.F90
  diag_manager/Makefile.am
  diag_manager/diag_axis.F90
  diag_manager/diag_data.F90
  diag_manager/diag_grid.F90
  diag_manager/diag_manager.F90
  diag_manager/diag_output.F90
  diag_manager/diag_util.F90
  drifters/drifters.F90
  drifters/drifters_core.F90
  drifters/drifters_input.F90
  exchange/xgrid.F90
  fms/fms_io.F90
  mpp/include/mpp_domains_comm.inc
  mpp/mpp_domains.F90
  mpp/mpp_pset.F90
Labels: bug, enhancement

#367 FMS2io: domain_write fix
  fms2_io/include/domain_write.inc
Labels: bug

#387 added platform to some include paths
  coupler/Makefile.am
  exchange/Makefile.am
  interpolator/Makefile.am
  test_fms/data_override/Makefile.am
  test_fms/diag_manager/Makefile.am
  test_fms/interpolator/Makefile.am
Labels: bug

#388 update constants file by moving small_fac options
  constants/constants.F90
Labels: enhancement

#392 Fixing issue 383 - Axes for reginal diagnostics not written corrrectly.
  diag_manager/diag_output.F90
Labels: bug, new fms io

#385 Fms2io nml
  Makefile.am
  fms/Makefile.am
  fms/fms.F90
  fms2_io/blackboxio.F90
  fms2_io/fms2_io.F90
  fms2_io/netcdf_io.F90
Labels: enhancement, feature request, new fms io
